version: "3"
services:
  smatradernflx:
    container_name: smatradernflx
    image: smaalpacatrader:latest
    build: ./src
    command: bash -c "python predictor.py"
    env_file:
      - .alpacalogin
    environment: 
      - STOCK=NFLX
      - FastSMA=4
      - SlowSMA=3
      - MoneyDivide=5
    network_mode: "host"

  smatradermsft:
    container_name: smatradermsft
    image: smaalpacatrader:latest
    build: ./src
    command: bash -c "python predictor.py"
    env_file:
      - .alpacalogin
    environment: 
      - STOCK=MSFT
      - FastSMA=14
      - SlowSMA=10
      - MoneyDivide=5
    network_mode: "host"

  smatradergoog:
    container_name: smatradergoog
    image: smaalpacatrader:latest
    build: ./src
    command: bash -c "python predictor.py"
    env_file:
      - .alpacalogin
    environment: 
      - STOCK=GOOG
      - FastSMA=2
      - SlowSMA=33
      - MoneyDivide=5
    network_mode: "host"

  smatraderaapl:
    container_name: smatraderaapl
    image: smaalpacatrader:latest
    build: ./src
    command: bash -c "python predictor.py"
    env_file:
      - .alpacalogin
    environment: 
      - STOCK=AAPL
      - FastSMA=3
      - SlowSMA=12
      - MoneyDivide=5
    network_mode: "host"

  smatraderamzn:
    container_name: smatraderamzn
    image: smaalpacatrader:latest
    build: ./src
    command: bash -c "python predictor.py"
    env_file:
      - .alpacalogin
    environment: 
      - STOCK=AMZN
      - FastSMA=1
      - SlowSMA=3
      - MoneyDivide=5
    network_mode: "host"

